language: python
python:
  - "3.6"
  - "nightly"
  - "pypy3"
install:
  - pip install -r requirements.txt
script:
  - python week1/__init__.py
  - python week1/json_example.py
  - python week1/numpy_example.py
  - python week1/plot_example.py
  - python week1/requestlib.py
  - python week1/table.py